name: notes_app
description: A simple note-taking Flutter app.

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Downgraded to the compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <4.0.0"

flutter:
  uses-material-design: true
